export const RegRequests  = [

    {
        type: "organization",
        first_name: "John",
        last_name: "Doe",
        gender: "Male",
        email: "john.wick@example.com",
        password: "password123",
        contact_number: "+1234567890",
        organization: {
            name: "Example Charity",
            type: "Non-Profit",
            address: "123 Main Street",
            area: "Downtown",
            governorate: "New York"

        },
    },
    {
        type: "organization",
    first_name: "Jane",
    last_name: "Smith",
    gender: "Female",
    email: "jane.smith@example.com",
    password: "securepass321",
    contact_number: "+1987654321",
    organization: {
    name: "HealthCare Foundation",
        type: "Healthcare",
        address: "456 Elm Avenue",
        area: "Uptown",
        governorate: "California"
    }
},
    {
        type:"donor",
        first_name: "David",
        last_name: "Brown",
        gender: "Male",
        email: "david.brown@example.com",
        password: "donorpass456",
        contact_number: "+1122334455",
        indtype: "Doctor",
        address: "789 Oak Street",
        area: "Suburb",
        governorate: "Texas"
    },
    { type:"donor",
        first_name: "Sarah",
        last_name: "Johnson",
        gender: "Female",
        email: "sarah.johnson@example.com",
        password: "donorpass789",
        contact_number: "+9988776655",
        indtype: "Teacher",
        address: "101 Pine Lane",
        area: "Rural",
        governorate: "Florida"
    },
    { type:"donor",
        first_name: "Sarah",
        last_name: "Johnson",
        gender: "Female",
        email: "sarah.johnson@example.com",
        password: "donorpass789",
        contact_number: "+9988776655",
        indtype: "Teacher",
        address: "101 Pine Lane",
        area: "Rural",
        governorate: "Florida"
    },
    { type:"donor",
        first_name: "Sarah",
        last_name: "Johnson",
        gender: "Female",
        email: "sarah.johnson@example.com",
        password: "donorpass789",
        contact_number: "+9988776655",
        indtype: "Teacher",
        address: "101 Pine Lane",
        area: "Rural",
        governorate: "Florida"
    },
    { type:"donor",
        first_name: "Sarah",
        last_name: "Johnson",
        gender: "Female",
        email: "sarah.johnson@example.com",
        password: "donorpass789",
        contact_number: "+9988776655",
        indtype: "Teacher",
        address: "101 Pine Lane",
        area: "Rural",
        governorate: "Florida"
    },
    { type:"donor",
        first_name: "Sarah",
        last_name: "Johnson",
        gender: "Female",
        email: "sarah.johnson@example.com",
        password: "donorpass789",
        contact_number: "+9988776655",
        indtype: "Teacher",
        address: "101 Pine Lane",
        area: "Rural",
        governorate: "Florida"
    }
];
