export const IndividualUsers = [
    {
        userId: 1,
        firstName: "John",
        lastName: "Doe",
        gender: "Male",
        email: "john.doe@example.com",
        contactNumber: "1234567890",
        password: "password1",
        address: "123 Main St",
        area: "Downtown",
        governorate: "Cairo",
        type: "Teacher",
        location: {
            lat: 40.7128,
            lng: -74.0060,
        },
        subjects: "Math, Science, English",
        privateClasses:5,
        classes: 3,
        workingInfo: true,
        isVerified: true
    },
    {
        userId: 2,
        firstName: "Jane",
        lastName: "Doe",
        gender: "Female",
        email: "jane.doe@example.com",
        contactNumber: "0987654321",
        password: "password2",
        address: "456 Elm St",
        area: "Uptown",
        governorate: "Alexandria",
        type: "Doctor",
        location: {
            lat: 39.9526,
            lng: -75.1652,
        },
        clinicAddress: "101 Pine St",
        clinicArea: "Rural",
        clinicGovernorate: "Luxor",
        specialization: "Cardiologist",
        numOfCases: 3,
        workingInfo: true,
        isVerified: true
    },
    {
        userId: 3,
        firstName: "Michael",
        lastName: "Smith",
        gender: "Male",
        email: "michael.smith@example.com",
        contactNumber: "2345678901",
        password: "password3",
        address: "789 Oak St",
        area: "Suburbia",
        governorate: "Giza",
        type: "Teacher",
        location: {
            lat: 34.0522,
            lng: -118.2437,
        },
        subjects: "History, Geography, Civics",
        privateClasses:2,
        classes: 2,
        workingInfo: true,
        isVerified: false

    },
    {
        userId: 4,
        firstName: "Emily",
        lastName: "Johnson",
        gender: "Female",
        email: "emily.johnson@example.com",
        contactNumber: "3456789012",
        password: "password4",
        address: "101 Pine St",
        area: "Rural",
        governorate: "Luxor",
        type: "Doctor",
        location: {
            lat: 25.6872,
            lng: 32.6396,
        },
        clinicAddress: "202 Maple St",
        clinicArea: "Urban",
        clinicGovernorate: "Aswan",
        specialization: "Pediatrician",
        numOfCases: 5,
        workingInfo: true,
        isVerified: true
    },
    {
        userId: 5,
        firstName: "David",
        lastName: "Williams",
        gender: "Male",
        email: "david.williams@example.com",
        contactNumber: "4567890123",
        password: "password5",
        address: "202 Maple St",
        area: "Urban",
        governorate: "Aswan",
        type: "Regular",
        location: {
            lat: 24.0889,
            lng: 32.8998,
        },
        workingInfo: false,
        isVerified: false
    }
];